INSERT INTO factor VALUES 
('alcohol use', 'ALD - Alcoholic Liver Disease'),
('alcohol use', 'Acute Alcohol Intoxication'),
('alcohol use', 'Acute Alcohol Withdrawal'),
('alcohol use', 'Acute Alcoholic Hepatitis'),
('alcohol use', 'Addiction, Alcohol'),
('alcohol use', 'Alcohol'),
('alcohol use', 'Alcohol & Drug Use'),
('alcohol use', 'Alcohol Abstinence'),
('alcohol use', 'Alcohol Abuse'),
('alcohol use', 'Alcohol Abuse and Dependency'),
('alcohol use', 'Alcohol Abuse in Pregnancy'),
('alcohol use', 'Alcohol Abuse or Dependence'),
('alcohol use', 'Alcohol Abuse, Alcohol Dependence'),
('alcohol use', 'Alcohol Abuse, Episodic Drinking Behavior'),
('alcohol use', 'Alcohol Abuse, Nervous System'),
('alcohol use', 'Alcohol Abuse/Addiction'),
('alcohol use', 'Alcohol Abuse/Dependence'),
('alcohol use', 'Alcohol Addiction'),
('alcohol use', 'Alcohol Amnestic Disorder'),
('alcohol use', 'Alcohol Approach/Avoidance Task'),
('alcohol use', 'Alcohol Cessation Intervention'),
('alcohol use', 'Alcohol Concentration Values'),
('alcohol use', 'Alcohol Concentrations in Body Fluids'),
('alcohol use', 'Alcohol Consumption'),
('alcohol use', 'Alcohol Consumption, Youth'),
('alcohol use', 'Alcohol Craving'),
('alcohol use', 'Alcohol Dependance'),
('alcohol use', 'Alcohol Dependence'),
('alcohol use', 'Alcohol Dependence (Primary Condition)'),
('alcohol use', 'Alcohol Dependence, in Remission'),
('alcohol use', 'Alcohol Dependency'),
('alcohol use', 'Alcohol Dependent'),
('alcohol use', 'Alcohol Disorders'),
('alcohol use', 'Alcohol Drinking'),
('alcohol use', 'Alcohol Drinking Related Problems'),
('alcohol use', 'Alcohol Drinking in College'),
('alcohol use', 'Alcohol Drug Interactions'),
('alcohol use', 'Alcohol Effect'),
('alcohol use', 'Alcohol Exposed Pregnancy'),
('alcohol use', 'Alcohol Impaired Driving'),
('alcohol use', 'Alcohol Impairment'),
('alcohol use', 'Alcohol Intake'),
('alcohol use', 'Alcohol Intoxication'),
('alcohol use', 'Alcohol Misuse'),
('alcohol use', 'Alcohol Negative Consequences'),
('alcohol use', 'Alcohol Problem'),
('alcohol use', 'Alcohol Reactivity'),
('alcohol use', 'Alcohol Relapse Prevention'),
('alcohol use', 'Alcohol Related Ataxia'),
('alcohol use', 'Alcohol Related Disorders'),
('alcohol use', 'Alcohol Related Morbidity'),
('alcohol use', 'Alcohol Related Neurodevelopmental Disorder'),
('alcohol use', 'Alcohol Risk Behaviors'),
('alcohol use', 'Alcohol Sensitivity'),
('alcohol use', 'Alcohol Use'),
('alcohol use', 'Alcohol Use Among ART Clients'),
('alcohol use', 'Alcohol Use Complicating Pregnancy, Unspecified Trimester'),
('alcohol use', 'Alcohol Use Disorder'),
('alcohol use', 'Alcohol Use Disorder (AUD)'),
('alcohol use', 'Alcohol Use Disorder Cognitive Decline'),
('alcohol use', 'Alcohol Use Disorders'),
('alcohol use', 'Alcohol Use Disorders (AUD)'),
('alcohol use', 'Alcohol Use Disorders.'),
('alcohol use', 'Alcohol Use Norms'),
('alcohol use', 'Alcohol Use and STI/HIV Infections, Domestic Violence'),
('alcohol use', 'Alcohol Use, Unspecified'),
('alcohol use', 'Alcohol Use/Abuse'),
('alcohol use', 'Alcohol Withdrawal'),
('alcohol use', 'Alcohol Withdrawal Associated Autonomic Hyperactivity'),
('alcohol use', 'Alcohol Withdrawal Delirium'),
('alcohol use', 'Alcohol Withdrawal Hallucinosis'),
('alcohol use', 'Alcohol Withdrawal State'),
('alcohol use', 'Alcohol Withdrawal Syndrome'),
('alcohol use', 'Alcohol Withdrawal Syndrome(AWS)'),
('alcohol use', 'Alcohol Withdrawal-Induced Delirium Tremens'),
('alcohol use', 'Alcohol Withdrawl'),
('alcohol use', 'Alcohol and Drug Abuse'),
('alcohol use', 'Alcohol and Drug Screening'),
('alcohol use', 'Alcohol and Drug Use'),
('alcohol use', 'Alcohol and Other Drug Use Disorders'),
('alcohol use', 'Alcohol and Other Substance Use Prevention'),
('alcohol use', 'Alcohol and Substance-Related Mental Disorders'),
('alcohol use', 'Alcohol in Breastmilk'),
('alcohol use', 'Alcohol or Other Drugs Effects'),
('alcohol use', 'Alcohol or Other Drugs Use'),
('alcohol use', 'Alcohol, Drinking'),
('alcohol use', 'Alcohol-Induced Disorders'),
('alcohol use', 'Alcohol-Induced Disorders, Nervous System'),
('alcohol use', 'Alcohol-Related Disorders'),
('alcohol use', 'Alcohol-abuse'),
('alcohol use', 'Alcohol-dependence'),
('alcohol use', 'Alcohol-induced Cue-craving'),
('alcohol use', 'Alcohol-induced Disorders'),
('alcohol use', 'Alcohol-related Disorders'),
('alcohol use', 'Alcohol-related Liver Disease'),
('alcohol use', 'Alcohol-related Neurodevelopmental Disorder'),
('alcohol use', 'Alcohol; Harmful Use'),
('alcohol use', 'Alcohol; Use, Problem'),
('alcohol use', 'Alcoholic'),
('alcohol use', 'Alcoholic Cirrhosis'),
('alcohol use', 'Alcoholic Hepatitis'),
('alcohol use', 'Alcoholic Hepatitis (AH)'),
('alcohol use', 'Alcoholic Intoxication'),
('alcohol use', 'Alcoholic Intoxication, Chronic'),
('alcohol use', 'Alcoholic Liver Cirrhosis'),
('alcohol use', 'Alcoholic Liver Disease'),
('alcohol use', 'Alcoholic Liver Diseases'),
('alcohol use', 'Alcoholic Neuropathy'),
('alcohol use', 'Alcoholic Pancreatitis'),
('alcohol use', 'Alcoholic Patient'),
('alcohol use', 'Alcoholic Relapse'),
('alcohol use', 'Alcoholic or Viral C Compensated Cirrhosis'),
('alcohol use', 'Alcoholic, Marijuana Misuse'),
('alcohol use', 'Alcoholism'),
('alcohol use', 'Alcoholism,'),
('alcohol use', 'At-Risk-Drinking'),
('alcohol use', 'At-risk Drinking'),
('alcohol use', 'Attention Deficit Hyperactivity Disorder and Alcohol Dependence'),
('alcohol use', 'Behavior, Drinking'),
('alcohol use', 'Binge Drinking'),
('alcohol use', 'Binge Drinking, Underage Drinking, Drinking and Driving, Alcohol-Related Harms'),
('alcohol use', 'Bipolar I or II Depression and Alcohol Abuse or Dependence'),
('alcohol use', 'Cardiomyopathy, Alcoholic'),
('alcohol use', 'Chronic Alcoholic Hepatitis'),
('alcohol use', 'Chronic Alcoholism'),
('alcohol use', 'Co-Occurring Alcohol and Drug Misuse'),
('alcohol use', 'College Student Drinking'),
('alcohol use', 'Comorbid Alcohol Abuse'),
('alcohol use', 'Concurrent Alcohol Dependence and Pathological Gambling'),
('alcohol use', 'Drink Driving'),
('alcohol use', 'Drinking'),
('alcohol use', 'Drinking Behavior'),
('alcohol use', 'Drinking Behaviour'),
('alcohol use', 'Drinking Excessive'),
('alcohol use', 'Drinking Heavy'),
('alcohol use', 'Drinking and Driving'),
('alcohol use', 'Drinking to Cope'),
('alcohol use', 'Driving Under the Influence of Alcohol and Other Drugs'),
('alcohol use', 'Drug and Alcohol Abuse'),
('alcohol use', 'Excessive Alcohol Consumption'),
('alcohol use', 'Excessive Drinking'),
('alcohol use', 'Familial Alcoholism Vulnerability'),
('alcohol use', 'Family History of Alcoholism'),
('alcohol use', 'Fatty Liver, Alcoholic'),
('alcohol use', 'Focus: Effects of Nicotine and Alcohol on Brain Circuits'),
('alcohol use', 'Harmful Alcohol Use'),
('alcohol use', 'Harmful Drinking'),
('alcohol use', 'Harmful; Use, Alcohol'),
('alcohol use', 'Hazardous Alcohol Consumption'),
('alcohol use', 'Hazardous Alcohol Use'),
('alcohol use', 'Hazardous Drinking'),
('alcohol use', 'Hazardous and Harmful Alcohol Use'),
('alcohol use', 'Heavy Alcoholic Consumption'),
('alcohol use', 'Heavy Dose Drinkers'),
('alcohol use', 'Heavy Drinking'),
('alcohol use', 'Heavy Drinking Days'),
('alcohol use', 'Heavy Episodic Drinking'),
('alcohol use', 'Hemodynamic Effects of Energy Drink'),
('alcohol use', 'Hepatitis, Alcoholic'),
('alcohol use', 'High Risk Drinking'),
('alcohol use', 'High-risk Alcohol Consumption Pattern'),
('alcohol use', 'Intrahepatic Cholestasis Associated With Alcoholic Liver Disease'),
('alcohol use', 'Liver Cirrhosis, Alcoholic'),
('alcohol use', 'Liver Disease (Alcoholic or Not)'),
('alcohol use', 'Liver Disease, Alcoholic'),
('alcohol use', 'Liver Diseases, Alcoholic'),
('alcohol use', 'Low-risk Alcohol Consumption Pattern'),
('alcohol use', 'Mild to Heavy Alcohol Consumption'),
('alcohol use', 'Moderate Alcohol Consumption (1-3 Drinks Per Day)'),
('alcohol use', 'Nocturnal Eating-Drinking Syndrome'),
('alcohol use', 'Obesity, Weight Loss, Alcohol Drinking'),
('alcohol use', 'PTSD and Alcohol Use Disorder'),
('alcohol use', 'Patient Adherence, Chronic Hepatitis C, Alcohol-related Disorders'),
('alcohol use', 'Perceived Alcohol Intoxication'),
('alcohol use', 'Prenatal Alcohol Exposure'),
('alcohol use', 'Primary Alcohol Use Disorder'),
('alcohol use', 'Problem Drinking'),
('alcohol use', 'Problematic AOD (Alcohol and Drug) Use.'),
('alcohol use', 'Problematic Alcohol Use'),
('alcohol use', 'Problematic Alcohol Use.'),
('alcohol use', 'Problematic Use of Alcohol or Other Drugs'),
('alcohol use', 'Reduction in Heavy Drinking in Patients With HIV'),
('alcohol use', 'Risk Drinking,Diabetes, Hypertension, Osteoporosis, Infertility'),
('alcohol use', 'Risk Perception of Driving After Alcohol Consumption'),
('alcohol use', 'Risk for an Alcohol-Exposed Pregnancy'),
('alcohol use', 'Risky Alcohol Consumption'),
('alcohol use', 'Risky Alcohol Consumption Amounts'),
('alcohol use', 'Risky Drinking'),
('alcohol use', 'Seizure, Alcohol Related'),
('alcohol use', 'Severe Acute Alcoholic Hepatitis'),
('alcohol use', 'Severe Alcoholic Hepatitis'),
('alcohol use', 'Severe Alcoholic Hepatitis in ''Extremis''- Defined by mDF>54'),
('alcohol use', 'Short-term Abstinence From Alcohol Use (2 Week Abstinent)'),
('alcohol use', 'Social Drinker'),
('alcohol use', 'Substance Use (Drugs, Alcohol)'),
('alcohol use', 'The Sweat Alcohol Concentration'),
('alcohol use', 'Underage Alcohol Use'),
('alcohol use', 'Underage Drinking'),
('alcohol use', 'Unhealthy Alcohol Use'),
('alcohol use', 'Unhealthy Diet, Exercise, Smoking, and Alcohol Use'),
('alcohol use', 'Unhealthy Drinking'),
('alcohol use', 'Young Adult Alcohol Drinking'),
('alcohol use', 'Youth Drinking'),
('alcohol use', 'for Cigarette Smoking and Binge Drinking Cessation'),
('diet', '24-hour Dietary Recall'),
('diet', 'ADA Dietary Education'),
('diet', 'Adherence to Fad Diet (Symptom)'),
('diet', 'Change in Dietary Outcomes'),
('diet', 'Changes in Diet, Food, and Nutrition Habits'),
('diet', 'Children''s Diet Quality'),
('diet', 'Diet'),
('diet', 'Diet Condition: Before and After a Weight Loss Equivalent to What Patients Lose 1 Month After GBP 9approximately 10kg)'),
('diet', 'Diet Conditions'),
('diet', 'Diet Habit'),
('diet', 'Diet Induced Thermogenesis'),
('diet', 'Diet Intake Assessment'),
('diet', 'Diet Intervention'),
('diet', 'Diet Modification'),
('diet', 'Diet Records'),
('diet', 'Diet Surveys'),
('diet', 'Diet Therapy'),
('diet', 'Diet Tolerability'),
('diet', 'Diet and Human Microbiota'),
('diet', 'Diet, Carbohydrate-Restricted'),
('diet', 'Diet, Food, and Nutrition'),
('diet', 'Diet, Gluten-Free'),
('diet', 'Diet, High-Fat'),
('diet', 'Diet, High-Protein'),
('diet', 'Diet, Mediterranean'),
('diet', 'Diet, Polyphenols, Flavonoids, Stilbenes, Aged, Dementia, Alzheimer''s Disease, Epidemiology'),
('diet', 'Diet, Reducing'),
('diet', 'Diet, Sodium-Restricted'),
('diet', 'Diet-induced Thermogenesis'),
('diet', 'Dietary Adequacy'),
('diet', 'Dietary Allergy'),
('diet', 'Dietary Amenorrhea'),
('diet', 'Dietary Assessment'),
('diet', 'Dietary Assessment of Older Men'),
('diet', 'Dietary Behavior'),
('diet', 'Dietary Calcium Deficiency'),
('diet', 'Dietary Carcinogenesis'),
('diet', 'Dietary Deficiency'),
('diet', 'Dietary Diversity'),
('diet', 'Dietary Fat'),
('diet', 'Dietary Fats'),
('diet', 'Dietary Fiber'),
('diet', 'Dietary Fibers'),
('diet', 'Dietary Fructose Intolerance'),
('diet', 'Dietary Habits'),
('diet', 'Dietary Hyperoxaluria'),
('diet', 'Dietary Intake'),
('diet', 'Dietary Intake of Branched Chain Amino Acids'),
('diet', 'Dietary Intervention'),
('diet', 'Dietary Interventions'),
('diet', 'Dietary Iodine Deficiency'),
('diet', 'Dietary Manipulation'),
('diet', 'Dietary Modification'),
('diet', 'Dietary Modifications'),
('diet', 'Dietary Prevention'),
('diet', 'Dietary Protein'),
('diet', 'Dietary Proteins'),
('diet', 'Dietary Recommendations'),
('diet', 'Dietary Restraint'),
('diet', 'Dietary Rice Bran Supplementation'),
('diet', 'Dietary Selenium Deficiency'),
('diet', 'Dietary Sources of Sodium Intake'),
('diet', 'Dietary Supplement'),
('diet', 'Dietary Supplementation'),
('diet', 'Dietary Supplementation During Exercise'),
('diet', 'Dietary Supplementations'),
('diet', 'Dietary Supplements'),
('diet', 'Dietary Zinc Absorption'),
('diet', 'Dietary Zinc Deficiency'),
('diet', 'Dietary and Nutritional Therapies'),
('diet', 'Dietetic Intake'),
('diet', 'Effect of Diet on Microbiome Composition'),
('diet', 'Effects of Low FODMAP Diet Versus Gluten-free Diet on IBS Symptoms in Children'),
('diet', 'Endocrine and Metabolic Responses to Exercise and Diets'),
('diet', 'Evidence of Adaptation to Dietary Exposure to Fructans'),
('diet', 'Excessive Diet Restriction'),
('diet', 'Fasting Mimicking Diet'),
('diet', 'Generally Healthy Kids Consumption Soy Protein Foods as Part of Daily Diet'),
('diet', 'Genotype, Metabotype and Dietary Habits'),
('diet', 'Gut Microbial Responses to Dietary Fiber'),
('diet', 'Healthy Diet'),
('diet', 'High Protein Dietary Intake'),
('diet', 'High and Increasing Contribution of Energy From Beverages in the Diet May Enhance Positive Energy Balance and Weight Gain'),
('diet', 'Household Dietary Diversity'),
('diet', 'Improve Dietary Behaviors in Young Adults 21-30 Years of Age'),
('diet', 'Inherited Metabolic Diseases Requiring Restrictive and Specific Diet'),
('diet', 'Ketogen-based Therapeutic Diet'),
('diet', 'Ketogenic Diet'),
('diet', 'Ketogenic Dieting'),
('diet', 'Loeys-Dietz Syndrome'),
('diet', 'Low Protein Diet'),
('diet', 'Low Protein Dietary Intake'),
('diet', 'Low-Calorie Diet'),
('diet', 'Low-GI Dietary Education'),
('diet', 'Low-Reside Diet'),
('diet', 'Mediterranean Diet'),
('diet', 'Mediterranean, Diet'),
('diet', 'Metabolic Response to Dietary Modification'),
('diet', 'Monitoring Adherence to the Gluten-free Diet in Celiac Disease Patients'),
('diet', 'Poor Diet'),
('diet', 'Restricted Diet'),
('diet', 'Safety of Cobalt Dietary Supplementation'),
('diet', 'Spicy Diet'),
('diet', 'Standardized Diet'),
('diet', 'Unhealthy Diet'),
('diet', 'Unhealthy Diet, Exercise, Smoking, and Alcohol Use'),
('diet', 'Value of the Bowel Preparation and Diet Change Versus no Intervention'),
('diet', 'Vegan Diet'),
('diet', 'Very Low Calorie Diet'),
('diet', 'to Improve the Effectiveness of a Amino Acid Dietary Supplement in Chronic Pharyngeal Infections vs Placebo'),
('lifestyle', 'Active Lifestyle Males'),
('lifestyle', 'Behavioral Lifestyle Change'),
('lifestyle', 'Chronic Diseases of Lifestyle'),
('lifestyle', 'Exercise'),
('lifestyle', 'Exercise (EX)'),
('lifestyle', 'Exercise Promotion'),
('lifestyle', 'Healthy Lifestyle'),
('lifestyle', 'Healthy Lifestyle Behaviors'),
('lifestyle', 'Healthy Lifestyle Habits'),
('lifestyle', 'Inactive Lifestyle Males'),
('lifestyle', 'Inactivity/Low Levels of Exercise'),
('lifestyle', 'Intense Exercise'),
('lifestyle', 'Lifestyle'),
('lifestyle', 'Lifestyle Exercise'),
('lifestyle', 'Lifestyle Factors'),
('lifestyle', 'Lifestyle Intervention'),
('lifestyle', 'Lifestyle Intervention for at Least 1 Month'),
('lifestyle', 'Lifestyle Modification'),
('lifestyle', 'Lifestyle Risk Reduction'),
('lifestyle', 'Lifestyle, Sedentary'),
('lifestyle', 'Lifestyle-Related Condition'),
('lifestyle', 'Lifestyle-related Condition'),
('lifestyle', 'Lifestyles'),
('lifestyle', 'Sedentary Lifestyle'),
('lifestyle', 'Sedentary Lifestyle in Patients Over 70'),
('lifestyle', 'Sedentary Lifestyle; Obesity; General Well-being'),
('lifestyle', 'Unhealthy Diet, Exercise, Smoking, and Alcohol Use'),
('lifestyle', 'Unhealthy Lifestyle of Persons With Mental Disorders'),
('lifestyle', 'Weight Lifting'),
('lifestyle', 'Weight-Lifting Exercise Program'),
('nutrition', 'Acute Malnutrition'),
('nutrition', 'Adult Patients in Need of High-energy Oral Nutritional Supplementation'),
('nutrition', 'Aluminum Contamination of Parenteral Nutrition'),
('nutrition', 'Anemia; Deficiency, Nutritional, With Poor Iron Absorption'),
('nutrition', 'Appetite and General Nutritional Disorders'),
('nutrition', 'Balanced Nutrition'),
('nutrition', 'Cancer-related Malnutrition'),
('nutrition', 'Changes in Diet, Food, and Nutrition Habits'),
('nutrition', 'Child Acute Malnutrition'),
('nutrition', 'Child Malnutrition'),
('nutrition', 'Child Nutrition'),
('nutrition', 'Child Nutrition Disorders'),
('nutrition', 'Child Nutrition Sciences'),
('nutrition', 'Child Nutrition, Child Neurobehavioral Development'),
('nutrition', 'Child Nutritional Status'),
('nutrition', 'Child Overnutrition'),
('nutrition', 'Children - Malnutrition'),
('nutrition', 'Children Behavior About Nutrition'),
('nutrition', 'Children''s Nutrition Intake'),
('nutrition', 'Cholestasis of Parenteral Nutrition'),
('nutrition', 'Clinical and Nutritional Safety.'),
('nutrition', 'Community Based Nutritional Management'),
('nutrition', 'Compare Two Nutrition Screening Tools'),
('nutrition', 'Continuity of Nutritional Care'),
('nutrition', 'Critical Ill Patient Undergone Parenteral Nutrition'),
('nutrition', 'Denutrition'),
('nutrition', 'Diabetic Patients With Gastrointestinal Cancer Undergoing Surgery and Receiving Parenteral Nutrition'),
('nutrition', 'Diarrhea, Malnutrition'),
('nutrition', 'Diet, Food, and Nutrition'),
('nutrition', 'Dietary and Nutritional Therapies'),
('nutrition', 'Duration of Parenteral Nutrition'),
('nutrition', 'Dwarf - Nutritional'),
('nutrition', 'Eating Disorders'),
('nutrition', 'Effect of Individualized Nutrition on Quality of Life'),
('nutrition', 'Effect of Nutritional Supplements on Healthy Volunteers.'),
('nutrition', 'Efficacy of Exclusive Enteral Nutrition in Adult Active Crohn''s Disease With Complications or Failure of Medical Treatment'),
('nutrition', 'Exercise Nutritional Physiology'),
('nutrition', 'Focus: Nutritional Requirements for Infants'),
('nutrition', 'General Nutrition Disorder'),
('nutrition', 'General Nutritional Status'),
('nutrition', 'Global Acute Malnutrition (GAM)'),
('nutrition', 'Growth; Stunting, Nutritional'),
('nutrition', 'Hemodialysis Nutritional Risk Stratification'),
('nutrition', 'Home Parenteral Nutrition'),
('nutrition', 'IMMUNONUTRITION'),
('nutrition', 'Immigrant Physical Activity and Nutrition'),
('nutrition', 'Immunonutrition'),
('nutrition', 'Improving Maternal Nutrition Knowledge'),
('nutrition', 'Improving Young Child Nutrition'),
('nutrition', 'Infant Malnutrition'),
('nutrition', 'Infant Nutrition'),
('nutrition', 'Infant Nutrition Disorder'),
('nutrition', 'Infant Nutrition Disorders'),
('nutrition', 'Infant Nutrition Sciences'),
('nutrition', 'Infant Nutritional Sciences'),
('nutrition', 'Infant Overnutrition'),
('nutrition', 'Infant, Premature, Nutrition'),
('nutrition', 'Lack of; Care, Infant (Child), Malnutrition'),
('nutrition', 'Lipid Overnutrition'),
('nutrition', 'Long-term Parenteral Nutrition (2 Years) in Children and Adults'),
('nutrition', 'Malnutrition'),
('nutrition', 'Malnutrition (Calorie)'),
('nutrition', 'Malnutrition Severe'),
('nutrition', 'Malnutrition in Children'),
('nutrition', 'Malnutrition in the Elderly'),
('nutrition', 'Malnutrition of Mild Degree'),
('nutrition', 'Malnutrition or Risk of Malnutrition'),
('nutrition', 'Malnutrition, Child'),
('nutrition', 'Malnutrition, Infant'),
('nutrition', 'Malnutrition-Inflammation Syndrome'),
('nutrition', 'Malnutrition;'),
('nutrition', 'Malnutrition; Anemia'),
('nutrition', 'Malnutrition; Degree, Moderate'),
('nutrition', 'Malnutrition; Diabetes'),
('nutrition', 'Malnutrition; Protein'),
('nutrition', 'Malnutrition; Protein, Caloric, Severe'),
('nutrition', 'Maternal Malnutrition'),
('nutrition', 'Maternal Nutrition'),
('nutrition', 'Maternal Nutrition Knowledge and Practices'),
('nutrition', 'Maternal; Malnutrition'),
('nutrition', 'Metabolic and Nutritional Complications'),
('nutrition', 'Metabolic and Nutritional Disorders'),
('nutrition', 'Metabolism and Nutrition Disorder'),
('nutrition', 'Metabolism and Nutrition Disorders'),
('nutrition', 'Mild Insufficient Nutrition'),
('nutrition', 'Moderate Acute Malnutrition'),
('nutrition', 'Moderate Acute Malnutrition (MAM)'),
('nutrition', 'Moderate Malnutrition'),
('nutrition', 'Moderate and Severe Undernutrition'),
('nutrition', 'Nutrition'),
('nutrition', 'Nutrition Assessment'),
('nutrition', 'Nutrition Deficiency Due to Insufficient Food'),
('nutrition', 'Nutrition Deficiency(VitB1 VitB12.Ca.Fe)'),
('nutrition', 'Nutrition Disorder'),
('nutrition', 'Nutrition Disorder, Child'),
('nutrition', 'Nutrition Disorders'),
('tobacco use', 'Non-Smoking'),
('nutrition', 'Nutrition Disorders in Old Age'),
('nutrition', 'Nutrition Disorders, Child'),
('nutrition', 'Nutrition Intake'),
('nutrition', 'Nutrition Intervention'),
('nutrition', 'Nutrition Knowledge'),
('nutrition', 'Nutrition Labeling'),
('nutrition', 'Nutrition Physiological Phenomena'),
('nutrition', 'Nutrition Policy'),
('nutrition', 'Nutrition Poor'),
('nutrition', 'Nutrition Processes'),
('nutrition', 'Nutrition Related Cancer'),
('nutrition', 'Nutrition Status'),
('nutrition', 'Nutrition Support'),
('nutrition', 'Nutrition Therapy'),
('nutrition', 'Nutrition Therapy for Critical Illness'),
('nutrition', 'Nutrition of Preterm Infants'),
('nutrition', 'Nutrition, Oral Health'),
('nutrition', 'Nutritional Anemia'),
('nutrition', 'Nutritional Anemia in Infants.'),
('nutrition', 'Nutritional Anemia in Mothers.'),
('nutrition', 'Nutritional Assessment'),
('nutrition', 'Nutritional Deficiencies'),
('nutrition', 'Nutritional Deficiency'),
('nutrition', 'Nutritional Depletion'),
('nutrition', 'Nutritional Disease'),
('nutrition', 'Nutritional Disorder'),
('nutrition', 'Nutritional Disorders'),
('nutrition', 'Nutritional Failure'),
('nutrition', 'Nutritional Insufficiency'),
('nutrition', 'Nutritional Intervention'),
('nutrition', 'Nutritional Outcome of Nursing Home Residents'),
('nutrition', 'Nutritional Physiological Phenomena'),
('nutrition', 'Nutritional Quality'),
('nutrition', 'Nutritional Quality of Food Purchases'),
('nutrition', 'Nutritional Requirements'),
('nutrition', 'Nutritional Rickets'),
('nutrition', 'Nutritional Risk'),
('nutrition', 'Nutritional Safety'),
('nutrition', 'Nutritional Status'),
('nutrition', 'Nutritional Status at the Release of ICU.'),
('nutrition', 'Nutritional Status in Hospitalised Geriatric Patients'),
('nutrition', 'Nutritional Stunting'),
('nutrition', 'Nutritional Supplement'),
('nutrition', 'Nutritional Supplement Toxicity'),
('nutrition', 'Nutritional Supplements'),
('nutrition', 'Nutritional Support'),
('nutrition', 'Nutritional Wasting'),
('nutrition', 'Nutritional and Metabolic Disease'),
('nutrition', 'Nutritional and Metabolic Diseases'),
('nutrition', 'Obesity, Diabetes, Nutrition, Physical Health'),
('nutrition', 'Optimal Anabolic Nutrition Interventions'),
('nutrition', 'Oral Nutritional Supplementation'),
('nutrition', 'Other Endocrine/Nutritional/Metabolic Disorder'),
('nutrition', 'Other Malnutrition'),
('nutrition', 'Other Nutritional Deficiencies'),
('nutrition', 'Overnutrition'),
('nutrition', 'PARENTERAL NUTRITION'),
('nutrition', 'Parenteral Nutrition'),
('nutrition', 'Parenteral Nutrition (No Primary Condition Studied)'),
('nutrition', 'Parenteral Nutrition Associated Cholestasis'),
('nutrition', 'Parenteral Nutrition Associated Liver Disease'),
('nutrition', 'Parenteral Nutrition Associated Liver Disease (PNALD)'),
('nutrition', 'Parenteral Nutrition Associated Liver Disease PNALD'),
('nutrition', 'Parenteral Nutrition for Patients With Proven Insufficient Enteral Resorption'),
('nutrition', 'Parenteral Nutrition n-3 Fatty Acids'),
('nutrition', 'Parenteral Nutrition, Home'),
('nutrition', 'Parenteral Nutrition-Associated Liver Disease'),
('nutrition', 'Patients Requiring Artificial Nutrition'),
('nutrition', 'Patients Requiring Home Parenteral Nutrition'),
('nutrition', 'Physical Activity and Nutrition'),
('nutrition', 'Poor Nutrition'),
('nutrition', 'Poverty, Low Income, Food Insecurity, Undernutrition'),
('nutrition', 'Protein Malnutrition'),
('nutrition', 'Protein-Energy Malnutrition'),
('nutrition', 'Protein-energy Malnutrition'),
('nutrition', 'Risk of Malnutrition'),
('nutrition', 'School Feeding Programs and Nutrition Supplements'),
('nutrition', 'Severe Acute Malnutrition'),
('nutrition', 'Severe Acute Malnutrition in Childhood'),
('nutrition', 'Severe Insufficient Nutrition'),
('nutrition', 'Severe Malnutrition'),
('nutrition', 'Severe and Moderate Malnutrition'),
('nutrition', 'Sports Nutritional Physiological Phenomena'),
('nutrition', 'Sports Nutritional Sciences'),
('nutrition', 'Study Not Related to a Disease. Nutrition Study Without Drug Administration.'),
('nutrition', 'Surgical Infants Requiring Total Parenteral Nutrition'),
('nutrition', 'Systemic Nutritional Management'),
('nutrition', 'Total Parenteral Nutrition'),
('nutrition', 'Total Parenteral Nutrition-Induced Cholestasis'),
('nutrition', 'Total Parenteral Nutrition-induced Cholestasis'),
('nutrition', 'Uncomplicated Severe Acute Malnutrition'),
('nutrition', 'Under Nutrition'),
('nutrition', 'Under-nutrition'),
('nutrition', 'Undernutrition'),
('nutrition', 'Vitamin/Nutritional Deficiency'),
('nutrition', 'Vitamin; Excess Vitamin D (Nutritional)'),
('nutrition', 'Wasting and Malnutrition'),
('sexual activity', 'Adolescent Sexual Risk Behaviors'),
('sexual activity', 'Condomless Sex'),
('sexual activity', 'High Risk Sex'),
('sexual activity', 'High Risk Sex Behavior'),
('sexual activity', 'High-risk Sex'),
('sexual activity', 'RIsky Sexual Behavior'),
('sexual activity', 'Risky Sex Prevention'),
('sexual activity', 'Risky Sexual Behavior'),
('sexual activity', 'Sex, Unsafe'),
('sexual activity', 'Sexual Addiction'),
('sexual activity', 'Sexual Risk'),
('sexual activity', 'Sexual Risk Behavior'),
('sexual activity', 'Sexual Risk Behavior for HIV-Infection'),
('sexual activity', 'Sexual Risk Behaviors'),
('sexual activity', 'Sexual Risk Reduction'),
('sexual activity', 'Sexual Risk-taking Behaviors'),
('tobacco use', 'Non-asthmatic Smokers'),
('sexual activity', 'Sexual Transmission of Infection'),
('sexual activity', 'Sexually Transmitted Disease'),
('sexual activity', 'Sexually Transmitted Disease (STD)'),
('sexual activity', 'Sexually Transmitted Diseases'),
('sexual activity', 'Sexually Transmitted Diseases, Bacterial'),
('sexual activity', 'Sexually Transmitted Diseases, Viral'),
('sexual activity', 'Sexually Transmitted Infection'),
('sexual activity', 'Sexually Transmitted Infection (STI)'),
('sexual activity', 'Sexually Transmitted Infections'),
('sexual activity', 'Sexually Transmitted Infections (Not HIV or Hepatitis)'),
('sexual activity', 'Sexually Transmitted Infections (STI)'),
('sexual activity', 'Sexually Transmitted Infections (STIs)'),
('sexual activity', 'Teen Sexual Health'),
('sexual activity', 'Unprotected Sex'),
('sexual activity', 'Unsafe Sex'),
('sexual activity', 'Unsafe Sexual Behavior'),
('substance abuse', 'Abnormal Craving for Drugs'),
('substance abuse', 'Active or Ex-injection Drug Users'),
('substance abuse', 'Acute Opioid Withdrawal Syndrome'),
('substance abuse', 'Addict Heroin'),
('substance abuse', 'Addiction, Substance'),
('substance abuse', 'Adolescent Substance Abuse'),
('substance abuse', 'Adolescent Substance Use'),
('substance abuse', 'Adult Opioid-Dependence'),
('substance abuse', 'Alcohol & Drug Use'),
('substance abuse', 'Alcohol Drug Interactions'),
('substance abuse', 'Alcohol and Drug Abuse'),
('substance abuse', 'Alcohol and Drug Screening'),
('substance abuse', 'Alcohol and Drug Use'),
('substance abuse', 'Alcohol and Other Drug Use Disorders'),
('substance abuse', 'Alcohol and Other Substance Use Prevention'),
('substance abuse', 'Alcohol and Substance-Related Mental Disorders'),
('substance abuse', 'Alcohol or Other Drugs Effects'),
('substance abuse', 'Alcohol or Other Drugs Use'),
('substance abuse', 'Analgesic Drug Dependence'),
('substance abuse', 'Analgesic Drugs'),
('substance abuse', 'Chronic Opioid Use'),
('substance abuse', 'Cigarette Smoking Among Patients Currently Receiving Methadone or Buprenorphine Treatment for Opioid Dependence'),
('substance abuse', 'Co-Occurring Alcohol and Drug Misuse'),
('substance abuse', 'Co-occurring Mental and Substance Use Disorders'),
('substance abuse', 'Cocaine Use & Co-occuring Opioid Use Disorders'),
('substance abuse', 'Cognitively Healthy Subjects Influenced by Psychoactive Drugs'),
('substance abuse', 'Driving Under the Influence of Alcohol and Other Drugs'),
('substance abuse', 'Drug Abuse'),
('substance abuse', 'Drug Abuse Illicit'),
('substance abuse', 'Drug Abuse Prevention'),
('substance abuse', 'Drug Abuse, Intravenous'),
('substance abuse', 'Drug Abuse, Medication'),
('substance abuse', 'Drug Abuse/Dependence'),
('substance abuse', 'Drug Abuse/Dependency'),
('substance abuse', 'Drug Addiction'),
('substance abuse', 'Drug Dependence'),
('substance abuse', 'Drug Dependence,'),
('substance abuse', 'Drug Dependency'),
('substance abuse', 'Drug Habituation'),
('substance abuse', 'Drug Overdose'),
('substance abuse', 'Drug Relapse'),
('substance abuse', 'Drug Related Sleep Disturbance'),
('substance abuse', 'Drug Usage'),
('substance abuse', 'Drug Use'),
('substance abuse', 'Drug Use Disorder'),
('substance abuse', 'Drug Use Disorders'),
('substance abuse', 'Drug Users'),
('substance abuse', 'Drug Withdrawal Symptoms'),
('substance abuse', 'Drug-impaired Driving'),
('substance abuse', 'Drug/Substance Abuse/Addiction'),
('substance abuse', 'Drug; Withdrawal Symptoms, Neonatal'),
('substance abuse', 'Drugs of Abuse'),
('substance abuse', 'Early Satisfaction With Substance Dependence Care'),
('substance abuse', 'Ecstasy (Drug)'),
('substance abuse', 'Episodic Substance Use'),
('substance abuse', 'Genetic Underpinning of Substance Abuse'),
('substance abuse', 'Having Ever Injected Drugs'),
('substance abuse', 'Heroin Abuse'),
('substance abuse', 'Heroin Addiction'),
('substance abuse', 'Heroin Dependence'),
('substance abuse', 'Heroin Injection'),
('substance abuse', 'Heroin-addicted Patients Who Undertook Methadone Maintenance Treatment'),
('substance abuse', 'Hospitalized for Voluntary Drug Intoxication'),
('substance abuse', 'Illicit Drug Use'),
('substance abuse', 'Illicit Drug User'),
('substance abuse', 'Illicit Opioid Drug Use'),
('substance abuse', 'Illicit Substance Use'),
('substance abuse', 'Improving Treatment for Opioid Use Disorder in Courts'),
('substance abuse', 'Individual and Group Drug Counseling'),
('substance abuse', 'Injection Drug Use'),
('substance abuse', 'Intravenous Drug Abuse'),
('substance abuse', 'Intravenous Drug Users'),
('substance abuse', 'Maternal Opioid Use Disorder'),
('substance abuse', 'Maternal Substance Use'),
('substance abuse', 'Mental Health Issue (E.G., Depression, Psychosis, Personality Disorder, Substance Abuse)'),
('substance abuse', 'Mental and Behavioral Disorders Due to Multiple Drug Use and Use of Other Psychoactive Substances: Harmful Use'),
('substance abuse', 'Misuse of Prescription Only Drugs'),
('substance abuse', 'Moderate or Severe Opioid Use Disorder'),
('substance abuse', 'Morphinan Opioid Overdose'),
('substance abuse', 'Neonatal Opioid Withdrawal'),
('substance abuse', 'Non-Medical Opioid Use'),
('substance abuse', 'Nondependent Opioid Abuse, Episodic'),
('substance abuse', 'Obesity; Drug'),
('substance abuse', 'Opiod-Related Disorders'),
('substance abuse', 'Opioid'),
('substance abuse', 'Opioid Abuse'),
('substance abuse', 'Opioid Abuse or Dependence'),
('substance abuse', 'Opioid Abuse, Unspecified'),
('substance abuse', 'Opioid Abuse, Unspecified Use'),
('substance abuse', 'Opioid Addiction'),
('tobacco use', 'Non-smoker'),
('substance abuse', 'Opioid Analgesic Treatment Response'),
('substance abuse', 'Opioid Cessation'),
('substance abuse', 'Opioid Consumption'),
('substance abuse', 'Opioid Dependence'),
('substance abuse', 'Opioid Dependence, on Agonist Therapy'),
('substance abuse', 'Opioid Dependency'),
('substance abuse', 'Opioid Detoxification'),
('substance abuse', 'Opioid Exposed Infant'),
('substance abuse', 'Opioid Induced Constipation (OIC)'),
('substance abuse', 'Opioid Induced Motor Disturbances'),
('substance abuse', 'Opioid Intoxication'),
('substance abuse', 'Opioid Misuse'),
('substance abuse', 'Opioid Overdose'),
('substance abuse', 'Opioid Related Disorder'),
('substance abuse', 'Opioid Related Disorders'),
('substance abuse', 'Opioid Safety'),
('substance abuse', 'Opioid Substitution Treatment'),
('substance abuse', 'Opioid Tolerance, Opioid Naive, Opioid Exposure'),
('substance abuse', 'Opioid Use'),
('substance abuse', 'Opioid Use Disorder'),
('substance abuse', 'Opioid Use Disorders'),
('substance abuse', 'Opioid Use, Unspecified'),
('substance abuse', 'Opioid Use, Unspecified With Other Opioid-induced Disorder'),
('substance abuse', 'Opioid Use, Unspecified With Withdrawal'),
('substance abuse', 'Opioid Use, Unspecified, Uncomplicated'),
('substance abuse', 'Opioid Users'),
('substance abuse', 'Opioid Withdrawal'),
('substance abuse', 'Opioid-Dependence Among Adolescents'),
('substance abuse', 'Opioid-Induced Disorders'),
('substance abuse', 'Opioid-Induced Hyperalgesia'),
('substance abuse', 'Opioid-Related Disorders'),
('substance abuse', 'Opioid-Related Severe Adverse Drug Event'),
('substance abuse', 'Opioid-dependent and Methadone Treated Patients With Other Psychiatric'),
('substance abuse', 'Opioid-maintained Pregnant Women'),
('substance abuse', 'Opioid-related Disorders'),
('substance abuse', 'Opioid-use Disorder'),
('substance abuse', 'Opioids'),
('substance abuse', 'Opioids Use'),
('substance abuse', 'Opioids; Harmful Use'),
('substance abuse', 'Other (or Unknown) Substance Use Disorders'),
('substance abuse', 'Other Drug Substance Abuse'),
('substance abuse', 'Other Substance Abuse'),
('substance abuse', 'Other Substance Induced Sexual Dysfunction'),
('substance abuse', 'PTSD, Substance Use, and Attendance at Treatment'),
('substance abuse', 'Parenteral Drug Abuse'),
('substance abuse', 'Parenting Capacities of Substance Abusing Mothers'),
('substance abuse', 'Patients With Substance Abuse'),
('substance abuse', 'People Who Inject Drugs'),
('substance abuse', 'Perinatal Depression, Substance Use'),
('substance abuse', 'Poisoning by Psychoactive Substances'),
('substance abuse', 'Poly-substance Use'),
('substance abuse', 'Polysubstance Abuse'),
('substance abuse', 'Prenatal Drug Exposure'),
('substance abuse', 'Preoperative Screen for Substance Abuse in in Patients Undergoing Emergency Operation'),
('substance abuse', 'Prescription Drug Abuse'),
('substance abuse', 'Prescription Drug Abuse (Not Dependent)'),
('substance abuse', 'Prescription Opioid Abuse'),
('substance abuse', 'Prescription Opioid Dependence'),
('substance abuse', 'Prescription Opioid Misuse'),
('substance abuse', 'Prevalence of Psychoactive Substances in Road Traffic'),
('substance abuse', 'Prevention of Drug Abuse Risk'),
('substance abuse', 'Previous Illicit Drug Use'),
('substance abuse', 'Problematic AOD (Alcohol and Drug) Use.'),
('substance abuse', 'Problematic Opioid Use'),
('substance abuse', 'Problematic Use of Alcohol or Other Drugs'),
('substance abuse', 'Psychoactive Substances Consumers'),
('substance abuse', 'Psychoactive Substances Consumption'),
('substance abuse', 'Psychoactive Substances in Accident Involved Drivers'),
('substance abuse', 'Psychoses, Substance Induced'),
('substance abuse', 'Psychoses, Substance-Induced'),
('substance abuse', 'Psychotropic Drugs'),
('substance abuse', 'Recreational Drug Use'),
('substance abuse', 'Sniffs Drugs'),
('substance abuse', 'Social Harms in Substance Users in HIV Trials'),
('substance abuse', 'Sports Drug Abuse'),
('substance abuse', 'Stable Opioid Dependence'),
('substance abuse', 'Substance Abuse'),
('substance abuse', 'Substance Abuse Detection'),
('substance abuse', 'Substance Abuse Disorder'),
('substance abuse', 'Substance Abuse Disorders'),
('substance abuse', 'Substance Abuse Drug Chronic'),
('substance abuse', 'Substance Abuse Problem'),
('substance abuse', 'Substance Abuse Treatment Centers'),
('substance abuse', 'Substance Abuse Treatment for Adults'),
('substance abuse', 'Substance Abuse, Intravenous'),
('substance abuse', 'Substance Abuse/Addiction'),
('substance abuse', 'Substance Addiction'),
('substance abuse', 'Substance Dependence'),
('substance abuse', 'Substance Dependency'),
('substance abuse', 'Substance Misuse'),
('substance abuse', 'Substance P'),
('substance abuse', 'Substance Related Disorder'),
('substance abuse', 'Substance Related Disorders'),
('substance abuse', 'Substance Related Problem'),
('substance abuse', 'Substance Use'),
('substance abuse', 'Substance Use (Drugs, Alcohol)'),
('substance abuse', 'Substance Use Dependence'),
('substance abuse', 'Substance Use Disorder'),
('substance abuse', 'Substance Use Disorder (SUD)'),
('substance abuse', 'Substance Use Disorders'),
('substance abuse', 'Substance Use Prevention'),
('substance abuse', 'Substance Use Risks'),
('substance abuse', 'Substance Withdrawal Syndrome'),
('substance abuse', 'Substance, Addiction'),
('substance abuse', 'Substance- Related Disorder'),
('substance abuse', 'Substance-Induced Psychoses'),
('substance abuse', 'Substance-Related Disorders'),
('substance abuse', 'Substance-induced Cognitive Disorder'),
('substance abuse', 'Substance-induced Psychosis'),
('substance abuse', 'Substance-induced Sleep Disorder'),
('substance abuse', 'Substance-related Discorder'),
('substance abuse', 'Substance-related Disorder'),
('substance abuse', 'Substance-related Disorders'),
('substance abuse', 'Substances Used for a Hypnotic Purpose'),
('substance abuse', 'Vulnerability to Substance Addicition'),
('substance abuse', 'Vulnerability to Substance Addiction'),
('substance abuse', 'Withdrawal From Addictive Substance; Detoxification'),
('substance abuse', 'Youths At-risk for Drug Use/Abuse'),
('tobacco use', 'Active Smoker'),
('tobacco use', 'Addiction Nicotine'),
('tobacco use', 'Additional, Effective Methods to Stop Smoking'),
('tobacco use', 'Adolescent Smoking'),
('tobacco use', 'Adult Smokers'),
('tobacco use', 'Age Matched Healthy Volunteers (Non-smokers)'),
('tobacco use', 'Assessing and Creating Awareness About the Tobacco Law'),
('tobacco use', 'Asthma/COPD With Tobacco Dependence'),
('tobacco use', 'Asthmatic Smokers'),
('tobacco use', 'Basic Science Study of the Mechanisms of Attentional Enhancement by Compounds Acting on the Nicotinic Receptor'),
('tobacco use', 'Brain Reactivity of Non-smokers Undergoing fMRI Scanning'),
('tobacco use', 'Cancer and Tobacco Abuse'),
('tobacco use', 'Cannabis Smoking'),
('tobacco use', 'Carcinogenesis of the Nicotine'),
('tobacco use', 'Cessation of Smoking'),
('tobacco use', 'Cessation, Smoking'),
('tobacco use', 'Cessation, Tobacco'),
('tobacco use', 'Child Exposure to Tobacco Smoke'),
('tobacco use', 'Chronic Smokers'),
('tobacco use', 'Cigar Smoking'),
('tobacco use', 'Cigarette Addiction'),
('tobacco use', 'Cigarette Consumption'),
('tobacco use', 'Cigarette Craving'),
('tobacco use', 'Cigarette Smoker'),
('tobacco use', 'Cigarette Smokers'),
('tobacco use', 'Cigarette Smoking'),
('tobacco use', 'Cigarette Smoking Among Patients Currently Receiving Methadone or Buprenorphine Treatment for Opioid Dependence'),
('tobacco use', 'Cigarette Smoking Antepartum and Early Postpartum.'),
('tobacco use', 'Cigarette Smoking Behavior'),
('tobacco use', 'Cigarette Smoking Toxicity'),
('tobacco use', 'Cigarette-smoking'),
('tobacco use', 'Cigarettes'),
('tobacco use', 'Continued Smoking'),
('tobacco use', 'Current Smoker'),
('tobacco use', 'Current Smokers'),
('tobacco use', 'Current or Past Cigarette Smoker'),
('tobacco use', 'Dual Tobacco Use'),
('tobacco use', 'E-cigarette Smokers'),
('tobacco use', 'E-cigarettes'),
('tobacco use', 'Effects of Smoking on Infant'),
('tobacco use', 'Electronic Cigarette'),
('tobacco use', 'Electronic Cigarettes'),
('tobacco use', 'Environmental Tobacco Smoke'),
('tobacco use', 'Environmental Tobacco Smoke (ETS)'),
('tobacco use', 'Environmental Tobacco Smoke Exposure'),
('tobacco use', 'Explore Successful Method to Quit Smoking'),
('tobacco use', 'Exposure to Electronic Cigarettes'),
('tobacco use', 'Exposure to Environmental Smoke'),
('tobacco use', 'Exposure to Secondhand Smoke in Neonatal Infants'),
('tobacco use', 'Field Cancerization for Cannabis Smokers'),
('tobacco use', 'Focus: Effects of Nicotine and Alcohol on Brain Circuits'),
('tobacco use', 'Focus: Smoking Cessation as it Relates to Fracture Healing'),
('tobacco use', 'Focus: Surgical Smoke During Laparoscopic Surgery'),
('tobacco use', 'Former Smoker'),
('tobacco use', 'HEAVY TOBACCO SMOKERS'),
('tobacco use', 'Healthy Highly Dependant Smokers'),
('tobacco use', 'Healthy Lifetime Non-smokers'),
('tobacco use', 'Healthy Non-Smokers'),
('tobacco use', 'Healthy Non-smoker'),
('tobacco use', 'Healthy Smokers'),
('tobacco use', 'Healthy Volunteer Smokers'),
('tobacco use', 'Healthy Volunteers (Middle-aged Smokers)'),
('tobacco use', 'Healthy Volunteers (Non-smoker)'),
('tobacco use', 'Healthy Volunteers (Smoker)'),
('tobacco use', 'Heavy Smoker or Non-smoker'),
('tobacco use', 'Heavy Smoking'),
('tobacco use', 'Hookah Smoking'),
('tobacco use', 'Hospitalized Smokers'),
('tobacco use', 'In Utero Nicotine'),
('tobacco use', 'In-utero Nicotine'),
('tobacco use', 'Infant Environmental Tobacco Smoke Exposure'),
('tobacco use', 'Lung Smokers'),
('tobacco use', 'Maintenance of Smoking Cessation'),
('tobacco use', 'Marijuana Smoking'),
('tobacco use', 'Mental and Behavioral Disorders Due to Use of Tobacco'),
('tobacco use', 'Minority Smokers'),
('tobacco use', 'Moderate to Heavy Smokers'),
('tobacco use', 'Never Smoker'),
('tobacco use', 'Never Smokers'),
('tobacco use', 'Nicotine'),
('tobacco use', 'Nicotine Abuse'),
('tobacco use', 'Nicotine Addiction'),
('tobacco use', 'Nicotine Adverse Reaction'),
('tobacco use', 'Nicotine Anonymous'),
('tobacco use', 'Nicotine Craving'),
('tobacco use', 'Nicotine Dependance'),
('tobacco use', 'Nicotine Dependence'),
('tobacco use', 'Nicotine Dependence Tobacco Product'),
('tobacco use', 'Nicotine Dependence, Cigarettes'),
('tobacco use', 'Nicotine Dependence, Cigarettes, With Withdrawal'),
('tobacco use', 'Nicotine Dependence, Other Tobacco Product'),
('tobacco use', 'Nicotine Dependency'),
('tobacco use', 'Nicotine Dependent Cigarette Smoker'),
('tobacco use', 'Nicotine Exposure'),
('tobacco use', 'Nicotine Pharmacokinetic Study'),
('tobacco use', 'Nicotine Replacement Therapy'),
('tobacco use', 'Nicotine Transdermal System'),
('tobacco use', 'Nicotine Use Disorder'),
('tobacco use', 'Nicotine Withdrawal'),
('tobacco use', 'Nicotine Withdrawal Suppression'),
('tobacco use', 'Nicotine-free Hookah Smoking'),
('tobacco use', 'Non-smokers'),
('tobacco use', 'Non-smoking'),
('tobacco use', 'Non-smoking, Healthy Adults'),
('tobacco use', 'Oxidative Damage of DNA Due to Cigarette Smoking.'),
('tobacco use', 'PASSIVE SMOKING ,'),
('tobacco use', 'Parental Smoking'),
('tobacco use', 'Passive Smoking'),
('tobacco use', 'Past Smokers'),
('tobacco use', 'Rehabilitation; Tobacco Use'),
('tobacco use', 'Relapse to Smoking'),
('tobacco use', 'Response of Viral Infection to Woodsmoke'),
('tobacco use', 'Second Hand Smoke'),
('tobacco use', 'Second Hand Smoke Exposure'),
('tobacco use', 'Second Hand Tobacco Smoke'),
('tobacco use', 'Secondhand Smoke'),
('tobacco use', 'Secondhand Smoke Exposure'),
('tobacco use', 'Secondhand Smoking'),
('tobacco use', 'Smoke'),
('tobacco use', 'Smoke Exposure'),
('tobacco use', 'Smoke Induced Lung Disease'),
('tobacco use', 'Smoke Inhalation'),
('tobacco use', 'Smoke Inhalation Injury'),
('tobacco use', 'Smoke Inhalation Patients'),
('tobacco use', 'Smoke-related Lung Diseases'),
('tobacco use', 'Smokeless Tobacco'),
('tobacco use', 'Smokeless Tobacco Cessation'),
('tobacco use', 'Smokeless Tobacco Use'),
('tobacco use', 'Smoker'),
('tobacco use', 'Smoker Lung'),
('tobacco use', 'Smokers'),
('tobacco use', 'Smokers With Cancer'),
('tobacco use', 'Smokers at Risk of Lung Cancer'),
('tobacco use', 'Smokers, Elderly, Asthma, COPD, Recurrent Infections'),
('tobacco use', 'Smoking'),
('tobacco use', 'Smoking (Tobacco) Addiction'),
('tobacco use', 'Smoking Abstinence'),
('tobacco use', 'Smoking Addiction'),
('tobacco use', 'Smoking Among Youth'),
('tobacco use', 'Smoking Behavior'),
('tobacco use', 'Smoking Behavior in Schizophrenia'),
('tobacco use', 'Smoking Cessation'),
('tobacco use', 'Smoking Cessation Intervention'),
('tobacco use', 'Smoking Cessation and Lung Cancer'),
('tobacco use', 'Smoking Cessation; Tobacco Dependence'),
('tobacco use', 'Smoking Cue Reactivity'),
('tobacco use', 'Smoking Dependence'),
('tobacco use', 'Smoking Lapse Behavior'),
('tobacco use', 'Smoking Patients'),
('tobacco use', 'Smoking Prevention'),
('tobacco use', 'Smoking Reduction or Abstinence'),
('tobacco use', 'Smoking Relapse Behavior'),
('tobacco use', 'Smoking Related Diseases'),
('tobacco use', 'Smoking Status'),
('tobacco use', 'Smoking Tobacco'),
('tobacco use', 'Smoking Woman'),
('tobacco use', 'Smoking in Adolescents'),
('tobacco use', 'Smoking, Cigar'),
('tobacco use', 'Smoking, Cigarette'),
('tobacco use', 'Smoking, Healthy Volenteers'),
('tobacco use', 'Smoking, Hookah'),
('tobacco use', 'Smoking, Marijuana'),
('tobacco use', 'Smoking, Pipe'),
('tobacco use', 'Smoking, Tobacco'),
('tobacco use', 'Subjects at High Risk of Lung Cancer Due to Smoking'),
('tobacco use', 'Survey on Tobacco Control'),
('tobacco use', 'The Association Between Progesterone Levels and Smoking Related Symptomatology and Nicotine Cravings'),
('tobacco use', 'The Effects of Second-hand Smoke in New Borns'),
('tobacco use', 'The Study Focused on Reducing Tobacco Smoke Exposure for Child.'),
('tobacco use', 'To Test the Effectiveness of Different Incentive Models for Increasing the Follow-up Response Rate in the Current Smoker Subject'),
('tobacco use', 'Tobacco'),
('tobacco use', 'Tobacco Abstinence'),
('tobacco use', 'Tobacco Abstinence Syndrome'),
('tobacco use', 'Tobacco Abuse'),
('tobacco use', 'Tobacco Abuse Cigarette'),
('tobacco use', 'Tobacco Abuse Smoke'),
('tobacco use', 'Tobacco Addiction'),
('tobacco use', 'Tobacco Cessation'),
('tobacco use', 'Tobacco Consumption'),
('tobacco use', 'Tobacco Dependence'),
('tobacco use', 'Tobacco Industry Denormalisation Beliefs'),
('tobacco use', 'Tobacco Prevention'),
('tobacco use', 'Tobacco Prevention and Cessation'),
('tobacco use', 'Tobacco Product'),
('tobacco use', 'Tobacco Products'),
('tobacco use', 'Tobacco Reduction'),
('tobacco use', 'Tobacco Retraining of Automatic Approach'),
('tobacco use', 'Tobacco Smoke Exposure Pregnant Women'),
('tobacco use', 'Tobacco Smoke Pollution'),
('tobacco use', 'Tobacco Smokers'),
('tobacco use', 'Tobacco Smoking'),
('tobacco use', 'Tobacco Smoking Behavior'),
('tobacco use', 'Tobacco Smoking Cessation'),
('tobacco use', 'Tobacco Smoking in Depressed Patients'),
('tobacco use', 'Tobacco Smoking in Persons With Serious Mental Illness, Weight Management, Physical Activity'),
('tobacco use', 'Tobacco Smoking in Schizophrenic Patients'),
('tobacco use', 'Tobacco Toxicant Exposure'),
('tobacco use', 'Tobacco Toxicity'),
('tobacco use', 'Tobacco Use'),
('tobacco use', 'Tobacco Use Cessation'),
('tobacco use', 'Tobacco Use Disorder'),
('tobacco use', 'Tobacco Use Disorders'),
('tobacco use', 'Tobacco Use Treatment'),
('tobacco use', 'Tobacco Use and Smoking Behavior'),
('tobacco use', 'Tobacco Use in Childbirth'),
('tobacco use', 'Tobacco Use in Persons Living With HIV'),
('tobacco use', 'Tobacco Use in Persons Living With HIV (PLWH)'),
('tobacco use', 'Tobacco Withdrawal'),
('tobacco use', 'Tobacco, Smoking'),
('tobacco use', 'Tobacco-Related Carcinoma'),
('tobacco use', 'Tobacco-Use Disorder'),
('tobacco use', 'Tobacco-related Communications'),
('tobacco use', 'Tobacco; Use, Harmful'),
('tobacco use', 'Tobacco; Use, Rehabilitation'),
('tobacco use', 'Treatment-seeking Smokers, Reporting Consumption of at Least 10 Cigarettes'),
('tobacco use', 'Unhealthy Diet, Exercise, Smoking, and Alcohol Use'),
('tobacco use', 'Use and Dissemination of Smoking Cessation Intervention'),
('tobacco use', 'Use; Tobacco, Harmful'),
('tobacco use', 'Variation of the Antral Area After Cigarettes Smoking or Not'),
('tobacco use', 'Waterpipe Smoking'),
('tobacco use', 'Withdrawal Nicotine'),
('tobacco use', 'for Cigarette Smoking and Binge Drinking Cessation'),
('weight', 'Abnormal Weight Gain'),
('weight', 'Assess the Effect of an IR Reflexotherapy on Overweight and Class I Obese People'),
('weight', 'Asthma in Overweight Adults'),
('weight', 'Bariatric Surgery'),
('weight', 'Bariatric Surgery Candidate'),
('weight', 'Body Weight'),
('weight', 'Body Weight Change'),
('weight', 'Body Weight Changes'),
('weight', 'Body Weight Control'),
('weight', 'Body Weight Decreased'),
('weight', 'Body Weights'),
('weight', 'Body Weights and Measures'),
('weight', 'Child Overweight'),
('weight', 'Child Weight'),
('weight', 'Childhood Overweight'),
('weight', 'Chronic Weight Management'),
('weight', 'Development of Overweight/Obesity,'),
('weight', 'Diet Condition: Before and After a Weight Loss Equivalent to What Patients Lose 1 Month After GBP 9approximately 10kg)'),
('weight', 'Excess Weight'),
('weight', 'Excessive Weight Gain'),
('weight', 'Healthy Boys With no Emotional, Behavioral or Learning Problems Within a Normal Body Weight'),
('weight', 'Healthy Experienced Weight Training Males'),
('weight', 'Healthy Overweight Obese'),
('weight', 'Healthy and Overweight/ Obesity Males'),
('weight', 'Healthy, Overweight and/or Obese Subjects'),
('weight', 'High and Increasing Contribution of Energy From Beverages in the Diet May Enhance Positive Energy Balance and Weight Gain'),
('weight', 'Impact of Parent Intervention on Adolescent Weight Loss'),
('weight', 'Improve Weight Control, and Muscular and Cardiovascular Fitness'),
('weight', 'Inadequate Initial Weight Loss'),
('weight', 'Inadequate Weight Loss'),
('weight', 'Loss of Weight'),
('weight', 'Low Tidal Volume (6-8 mL/kg Predicted Body Weight)'),
('weight', 'Low Weight'),
('weight', 'Low Weight Eating Disorders'),
('weight', 'Low Weight for Age in Preschool Children'),
('weight', 'Maternal Post-partum Weight Retention'),
('weight', 'Moderately Overweight Individuals'),
('weight', 'Morbid Obesity'),
('weight', 'Normal Body Weight'),
('weight', 'Normal Weight'),
('weight', 'Normal Weight,Healthy Controls'),
('weight', 'OVERWEIGHT'),
('weight', 'Obese'),
('weight', 'Obesity /Overweight'),
('weight', 'Obesity and Overweight'),
('weight', 'Obesity, Acceptance and Commitment Therapy, Weight Management Service'),
('weight', 'Obesity, Morbid'),
('weight', 'Obesity, Weight Loss, Alcohol Drinking'),
('weight', 'Over Weight'),
('weight', 'Over-weight'),
('weight', 'Overweight'),
('weight', 'Overweight (BMI > 25)'),
('weight', 'Overweight Adolescents'),
('weight', 'Overweight Children With Type 2 Diabetes Risk'),
('weight', 'Overweight Management'),
('weight', 'Overweight Subjects'),
('weight', 'Overweight With Comorbidity'),
('weight', 'Overweight With Indications for Weight Loss'),
('weight', 'Overweight and Obese Volunteers.'),
('weight', 'Overweight and Obese Women'),
('weight', 'Overweight and Obesity'),
('weight', 'Overweight and Obesity in Schoolchildren'),
('weight', 'Overweight in Preschool Age Children'),
('weight', 'Overweight or Obese'),
('weight', 'Overweight or Obese Adults'),
('weight', 'Overweight or Obesity'),
('weight', 'Overweight,'),
('weight', 'Overweight, Obesity Grade I'),
('weight', 'Overweight, Obesity and Other Hyperalimentation (E65-E68)'),
('weight', 'Overweight, Obesity, Small for Gestational Age, Prematurity'),
('weight', 'Overweight/Obese Population'),
('weight', 'Overweight/Obese Women'),
('weight', 'Overweight/Obesity'),
('weight', 'Overweight: 25 <BMI <30'),
('weight', 'Overweight; Hyperlipidemia'),
('weight', 'Pediatric Overweight'),
('weight', 'People Who Are Overweight or Obesity'),
('weight', 'Percentage Body-Weight'),
('weight', 'Physiological Strain of Weight Bearing.'),
('weight', 'Poor Weight Loss'),
('weight', 'Prevent Further Weight Gain and or Promote'),
('weight', 'Prevention of Weight Gain'),
('weight', 'Psychotropic Induced Weight Gain'),
('weight', 'Risk of Overweight in Preschool Age Children'),
('weight', 'Severe Overweight'),
('weight', 'The Focus of Study is to Determine the Waist Circumference Values to Predict Overweight or Obesity'),
('weight', 'Tobacco Smoking in Persons With Serious Mental Illness, Weight Management, Physical Activity'),
('weight', 'Underweight'),
('weight', 'Weight'),
('weight', 'Weight Change'),
('weight', 'Weight Change, Body'),
('weight', 'Weight Changes'),
('weight', 'Weight Changes, Body'),
('weight', 'Weight Control'),
('weight', 'Weight Cycling'),
('weight', 'Weight Gain'),
('weight', 'Weight Lose'),
('weight', 'Weight Loss'),
('weight', 'Weight Loss Among Adolescents'),
('weight', 'Weight Loss Maintenance'),
('weight', 'Weight Loss Programs'),
('weight', 'Weight Loss Trial'),
('weight', 'Weight Maintenance'),
('weight', 'Weight Management'),
('weight', 'Weight Recidivism'),
('weight', 'Weight Reduction'),
('weight', 'Weight Reduction and Insulin Sensitivity'),
('weight', 'Weight Regain'),
('weight', 'Weight Regain Post Bariatric Surgery'),
('weight', 'Weight, Body'),
('weight', 'Weight-Bearing'),
('weight', 'Weight-Bearing Values'),
('weight', 'Weight-Estimation'),
('weight', 'Weight-Gain Prevention'),
('weight', 'Weightloss'),
('alcohol use', 'Alcoholic Fatty Liver Disease');


